service:
    path:     /
    defaults: { _controller: "CourriersBundle:Service:index" }

service_show:
    path:     /{id}/show
    defaults: { _controller: "CourriersBundle:Service:show" }

service_new:
    path:     /new
    defaults: { _controller: "CourriersBundle:Service:new" }

service_create:
    path:     /create
    defaults: { _controller: "CourriersBundle:Service:create" }
    methods:  POST

service_edit:
    path:     /{id}/edit
    defaults: { _controller: "CourriersBundle:Service:edit" }

service_update:
    path:     /{id}/update
    defaults: { _controller: "CourriersBundle:Service:update" }
    methods:  [POST, PUT]

service_delete:
    path:     /{id}/delete
    defaults: { _controller: "CourriersBundle:Service:delete" }
    methods:  [POST, DELETE]
