<?php

namespace DEA\CourriersBundle\Repository;

/**
 * ArriveeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArriveeRepository extends \Doctrine\ORM\EntityRepository
{
}
