<?php

namespace DEA\CourriersBundle\Repository;

/**
 * DepartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartRepository extends \Doctrine\ORM\EntityRepository
{
}
