<?php

namespace DEA\CourriersBundle\Repository;

/**
 * AffectdepartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffectdepartRepository extends \Doctrine\ORM\EntityRepository
{
}
