<?php

namespace DEA\CourriersBundle\Repository;

/**
 * AffectarriveeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffectarriveeRepository extends \Doctrine\ORM\EntityRepository
{
}
