<?php

namespace DEA\CourriersBundle\Repository;

/**
 * ArriveeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArriveeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllEntree(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT arrivee FROM CourriersBundle:Arrivee arrivee WHERE arrivee.flagaffect=0");
        $result = $query->getResult();

        return $result;
    }

    public function findAllTraite(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT arrivee FROM CourriersBundle:Arrivee arrivee WHERE arrivee.flagaffect=1 AND arrivee.flagtraite=1");
        $result = $query->getResult();

        return $result;
    }

    public function findAllValide(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT arrivee FROM CourriersBundle:Arrivee arrivee WHERE arrivee.flagaffect=1 AND arrivee.flagtraite=1 AND arrivee.flagvalide=0");
        $result = $query->getResult();

        return $result;
    }

    public function findAllRetard(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT arrivee FROM CourriersBundle:Arrivee arrivee WHERE arrivee.flagaffect=1 AND arrivee.flagtraite=0 AND arrivee.flagretard=1");
        $result = $query->getResult();

        return $result;
    }

    public function findAllArchive(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT arrivee FROM CourriersBundle:Arrivee arrivee WHERE arrivee.flagarchive=1");
        $result = $query->getResult();

        return $result;
    }
}
