<?php

namespace DEA\CourriersBundle\Repository;

/**
 * DepartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllEntree(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT depart FROM CourriersBundle:Depart depart WHERE depart.flagaffect=0");
        $result = $query->getResult();

        return $result;
    }

    public function findAllTraite(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT depart FROM CourriersBundle:Depart depart WHERE depart.flagaffect=1 AND depart.flagtraite=1");
        $result = $query->getResult();

        return $result;
    }

    public function findAllValide(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT depart FROM CourriersBundle:Depart depart WHERE depart.flagaffect=1 AND depart.flagtraite=1 AND depart.flagvalide=0");
        $result = $query->getResult();

        return $result;
    }

    public function findAllRetard(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT depart FROM CourriersBundle:Depart depart WHERE depart.flagaffect=1 AND depart.flagtraite=0 AND depart.flagretard=1");
        $result = $query->getResult();

        return $result;
    }

    public function findAllArchive(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT depart FROM CourriersBundle:Depart depart WHERE depart.flagarchive=1");
        $result = $query->getResult();

        return $result;
    }
}
